# ~/.config/fuzzel/fuzzel.ini

font=Monocraft:size=12
dpi-aware=auto
width=40
lines=8
horizontal-pad=16
vertical-pad=12
inner-pad=8
prompt="❯   "
icon-theme=Papirus-Dark
icons-enabled=yes
image-size-ratio=0.5
terminal=ghostty
match-mode=fzf
letter-spacing=0
use-bold=yes
match-counter=yes

[colors]
background=2b323cee
text=c9c4abff
prompt=7089a0ff
placeholder=4b5560ff
input=c9c4abff
message=4b5560ff
match=7089a0ff
selection=333b45ff
selection-text=e2ddc4ff
selection-match=7fa6a0ff
counter=4b5560ff
border=4b5560ff

[border]
width=1
radius=8

[dmenu]
exit-immediately-if-empty=yes
