# ~/.config/fuzzel/fuzzel.ini

font=Monocraft:size=12
dpi-aware=auto
width=40
lines=8
horizontal-pad=16
vertical-pad=12
inner-pad=8
prompt="❯   "
icon-theme=Papirus-Dark
icons-enabled=yes
image-size-ratio=0.5
terminal=ghostty
match-mode=fzf
letter-spacing=0
use-bold=yes
match-counter=yes

[colors]
background=2a3841ee
text=e3e7ebff
prompt=97d6ffff
placeholder=5a636aff
input=e3e7ebff
message=5a636aff
match=97d6ffff
selection=394149ff
selection-text=d2c7f0ff
selection-match=7fa6a0ff
counter=5a636aff
border=5a636aff

[border]
width=1
radius=8

[dmenu]
exit-immediately-if-empty=yes
