#!/usr/bin/env python3
"""Recolors the system to match the active wallpaper.

Run as: apply_theme_colors.py <wallpaper-relative-path, e.g. dark_sea.glsl>

Pipeline: render a wallpaper thumbnail already exists at
~/.config/driftwm/wallpapers/thumbs/ (gen_wallpaper_thumbs.sh) -> matugen
extracts a Material You palette from it -> we map a handful of matugen's
roles onto the small token set every themed file actually uses -> each
themed file is either rewritten whole (files that are 100% theme, nothing
else) or patched at specific known lines (files that mix theme with
unrelated settings, e.g. driftwm/config.toml or .zshrc).

Token contract (see also quickshell/Theme.qml, which carries the same six
color tokens for QML widgets):
    BG        background
    FG        text on BG
    BORDER    subtle borders/dividers
    TRACK     slightly-raised surface (selection bg, secondary panels)
    DARK      slightly-recessed surface (darker than BG)
    ACCENT    the one "brand" highlight color (active border, links, sliders)
    ON_ACCENT text drawn on top of an ACCENT-colored surface
    WARM      a second, distinct highlight (track titles, foam highlights)

Red/green/yellow/magenta/cyan (errors/warnings/git-status/ANSI colors) stay
FIXED across wallpapers on purpose — they carry meaning (error = red) that
shouldn't drift with the wallpaper, and Material You's role set doesn't
provide six independent hues to derive them from anyway.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

HOME = Path.home()
CFG = HOME / ".config"

FIXED = {
    "RED": "#b5665f", "RED_BR": "#c77a72",
    "GREEN": "#8a9a7c", "GREEN_BR": "#9dad8f",
    "YELLOW": "#c9b98a", "YELLOW_BR": "#dcccA0",
    "MAGENTA": "#9a8aa0", "MAGENTA_BR": "#ac9cb3",
    "CYAN": "#7fa6a0", "CYAN_BR": "#93bab4",
    "DIM": "#8f8a72", "PLACEHOLDER": "#6a6a5e",
}


def darken(hexcolor, factor):
    h = hexcolor.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
    return "#{:02x}{:02x}{:02x}".format(*(max(0, int(v * factor)) for v in (r, g, b)))


IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".webp", ".bmp"}


def thumb_for(wallpaper_rel):
    # A custom wallpaper picked via AppearanceSection's file dialog is
    # already a real photo — no shader thumbnail to render, use it as-is.
    direct = Path(wallpaper_rel).expanduser()
    if direct.is_absolute() and direct.suffix.lower() in IMAGE_SUFFIXES and direct.exists():
        return direct
    name = wallpaper_rel.replace("/", "_").replace(".glsl", ".png")
    p = CFG / "driftwm/wallpapers/thumbs" / name
    return p if p.exists() else CFG / "driftwm/wallpapers/thumbs/dark_sea.png"


def get_tokens(wallpaper_rel):
    thumb = thumb_for(wallpaper_rel)
    out = subprocess.run(
        ["matugen", "image", str(thumb), "--json", "hex", "--dry-run",
         "--mode", "dark", "--prefer", "darkness", "--lightness-dark", "0.15"],
        capture_output=True, text=True, check=True,
    ).stdout
    colors = json.loads(out)["colors"]
    role = lambda k: colors[k]["default"]["color"]
    t = {
        "BG": role("background"),
        "FG": role("on_background"),
        "BORDER": role("outline_variant"),
        "TRACK": role("surface_container"),
        "ACCENT": role("primary"),
        "ON_ACCENT": role("on_primary"),
        "WARM": role("tertiary"),
    }
    t["DARK"] = darken(t["BG"], 0.85)
    t.update(FIXED)
    return t


def w(path, content):
    Path(path).write_text(content)


# ---------------------------------------------------------------- kitty ----
def kitty(t):
    w(CFG / "kitty/colors.conf", f"""\
# ~/.config/kitty/colors.conf
# Regenerated by apply_theme_colors.py on every wallpaper switch.

background {t['BG']}
foreground {t['FG']}

cursor            {t['FG']}
cursor_text_color {t['BG']}

selection_background {t['TRACK']}
selection_foreground {t['WARM']}

# black
color0  {t['BG']}
color8  {t['BORDER']}
# red
color1  {t['RED']}
color9  {t['RED_BR']}
# green
color2  {t['GREEN']}
color10 {t['GREEN_BR']}
# yellow
color3  {t['YELLOW']}
color11 {t['YELLOW_BR']}
# blue
color4  {t['ACCENT']}
color12 {t['ACCENT']}
# magenta
color5  {t['MAGENTA']}
color13 {t['MAGENTA_BR']}
# cyan
color6  {t['CYAN']}
color14 {t['CYAN_BR']}
# white
color7  {t['FG']}
color15 {t['WARM']}

active_border_color   {t['ACCENT']}
inactive_border_color {t['BORDER']}
url_color             {t['ACCENT']}
""")


# -------------------------------------------------------------- ghostty ----
def ghostty(t):
    w(CFG / "ghostty/colors", f"""\
# ~/.config/ghostty/colors
# Regenerated by ~/.config/driftwm/scripts/apply_theme_colors.py on every
# wallpaper switch — hand edits here get overwritten, edit the script instead.

background = {t['BG'].lstrip('#')}
foreground = {t['FG'].lstrip('#')}

cursor-color = {t['FG'].lstrip('#')}
cursor-text = {t['BG'].lstrip('#')}

# Regular colors (0-7)
palette = 0={t['BG']}
palette = 1={t['RED']}
palette = 2={t['GREEN']}
palette = 3={t['YELLOW']}
palette = 4={t['ACCENT']}
palette = 5={t['MAGENTA']}
palette = 6={t['CYAN']}
palette = 7={t['FG']}

# Bright colors (8-15)
palette = 8={t['BORDER']}
palette = 9={t['RED_BR']}
palette = 10={t['GREEN_BR']}
palette = 11={t['YELLOW_BR']}
palette = 12={t['ACCENT']}
palette = 13={t['MAGENTA_BR']}
palette = 14={t['CYAN_BR']}
palette = 15={t['WARM']}
""")


# --------------------------------------------------------------- waybar ----
def waybar(t):
    w(CFG / "waybar/style.css", f"""\
/* ~/.config/waybar/style.css
   Regenerated by apply_theme_colors.py on every wallpaper switch. */

* {{
    font-family: "Monocraft";
    font-size: 13px;
    border: none;
    border-radius: 0;
    min-height: 0;
}}

window#waybar {{
    background-color: {t['BG']};
    color: {t['FG']};
    border-bottom: 1px solid {t['BORDER']};
}}

#workspaces button {{
padding: 0 8px;
color: {t['DIM']};
background: transparent;
}}

#workspaces button.active {{
color: {t['FG']};
background: {t['TRACK']};
border-bottom: 2px solid {t['ACCENT']};
}}

#workspaces button.urgent {{
color: {t['RED']};
}}

#clock,
#network,
#battery,
#tray,
#pulseaudio,
#cpu,
#memory,
#backlight,
#idle_inhibitor,
#custom-notification,
#custom-window {{
padding: 0 10px;
color: {t['FG']};
}}

#custom-window {{
color: {t['DIM']};
}}

#battery.warning {{
color: {t['YELLOW']};
}}

#battery.critical {{
color: {t['RED']};
}}

#network.disconnected {{
color: {t['RED']};
}}

#pulseaudio.muted {{
color: {t['BORDER']};
}}

#tray > .needs-attention {{
background-color: {t['RED']};
}}

tooltip {{
    background-color: {t['BG']};
    border: 1px solid {t['BORDER']};
}}

tooltip label {{
    color: {t['FG']};
}}
""")


# --------------------------------------------------------------- swaync ----
def swaync(t):
    w(CFG / "swaync/style.css", f"""\
/* ~/.config/swaync/style.css
   Regenerated by apply_theme_colors.py on every wallpaper switch. */

* {{
  font-family: "Monocraft";
}}

.control-center,
.notification-row .notification-background {{
  background: {t['BG']};
  color: {t['FG']};
  border: 1px solid {t['BORDER']};
  border-radius: 8px;
}}

.notification-row .notification-background .notification-default-action {{
  background: {t['BG']};
  color: {t['FG']};
}}

.notification-row .notification-background .notification-default-action:hover {{
  background: {t['TRACK']};
}}

.notification-action-container button,
.control-center .widget-buttons-grid button {{
  background: {t['TRACK']};
  color: {t['FG']};
  border: 1px solid {t['BORDER']};
}}

.control-center .widget-buttons-grid button:hover {{
  background: {t['BORDER']};
}}

.notification-row .close-button {{
  background: {t['RED']};
  color: {t['BG']};
}}

.control-center .widget-title button {{
  background: {t['TRACK']};
  color: {t['FG']};
}}

.control-center .widget-title label {{
  color: {t['FG']};
}}

.control-center slider {{
  background: {t['ACCENT']};
}}

.control-center scale trough {{
  background: {t['TRACK']};
}}

.control-center scale trough highlight {{
  background: {t['ACCENT']};
}}
""")


# ------------------------------------------------------------------ gtk ----
def gtk(t):
    content = f"""\
/* Тема Thunar под текущую системную палитру (driftwm/waybar/kitty).
   Regenerated by apply_theme_colors.py on every wallpaper switch. */

/* Основное окно с файлами */
.thunar thunar-standard-view,
.thunar .view,
thunar-window icon-view,
thunar-window thunar-standard-view {{
    background-color: {t['BG']} !important;
    color: {t['FG']} !important;
}}

/* Боковая панель (Места, Устройства) */
.thunar .sidebar,
thunar-window .sidebar,
.thunar scrolledwindow,
.thunar treeview {{
    background-color: {t['DARK']} !important;
    color: {t['FG']} !important;
}}

/* Строка меню верхняя (Файл, Правка, Вид...) */
thunar-window menu,
thunar-window menubar,
thunar-window menubar item {{
    background-color: {t['DARK']} !important;
    color: {t['FG']} !important;
}}

/* Панель инструментов (стрелочки назад/вперед, поиск) */
.thunar toolbar,
thunar-window toolbar {{
    background-color: {t['DARK']} !important;
    border-bottom: 1px solid {t['BORDER']} !important;
}}

/* Адресная строка (путь к папке) */
.thunar thunar-location-entry,
.thunar thunar-location-buttons,
.thunar entry {{
    background-color: {t['TRACK']} !important;
    color: {t['WARM']} !important;
    border: 1px solid {t['BORDER']} !important;
}}

/* Выделенные папки и элементы */
.thunar .view:selected,
.thunar .sidebar:selected,
.thunar treeview:selected,
.thunar icon-view:selected {{
    background-color: {t['ACCENT']} !important;
    color: {t['ON_ACCENT']} !important;
}}

/* Нижняя строка состояния */
thunar-window .statusbar,
.thunar statusbar {{
    background-color: {t['DARK']} !important;
    color: {t['CYAN']} !important;
}}
"""
    w(CFG / "gtk-3.0/gtk.css", content)
    w(CFG / "gtk-4.0/gtk.css", content)


# ------------------------------------------------------------------ btop ---
def btop(t):
    w(CFG / "btop/themes/dark_sea.theme", f"""\
# dark_sea — regenerated by apply_theme_colors.py on every wallpaper switch

theme[main_bg]="{t['BG']}"
theme[main_fg]="{t['FG']}"

theme[title]="{t['WARM']}"

theme[hi_fg]="{t['ACCENT']}"
theme[selected_bg]="{t['TRACK']}"
theme[selected_fg]="{t['WARM']}"

theme[inactive_fg]="{t['BORDER']}"
theme[graph_text]="{t['FG']}"

theme[proc_misc]="{t['CYAN']}"

theme[cpu_box]="{t['BORDER']}"
theme[mem_box]="{t['BORDER']}"
theme[net_box]="{t['BORDER']}"
theme[proc_box]="{t['BORDER']}"
theme[div_line]="{t['TRACK']}"

theme[temp_start]="{t['GREEN']}"
theme[temp_mid]="{t['YELLOW']}"
theme[temp_end]="{t['RED']}"

theme[cpu_start]="{t['CYAN']}"
theme[cpu_mid]="{t['ACCENT']}"
theme[cpu_end]="{t['MAGENTA']}"

theme[free_start]="{t['TRACK']}"
theme[free_mid]="{t['BORDER']}"
theme[free_end]="{t['CYAN']}"

theme[cached_start]="{t['TRACK']}"
theme[cached_mid]="{t['ACCENT']}"
theme[cached_end]="{t['ACCENT']}"

theme[available_start]="{t['TRACK']}"
theme[available_mid]="{t['YELLOW']}"
theme[available_end]="{t['YELLOW_BR']}"

theme[used_start]="{t['TRACK']}"
theme[used_mid]="{t['GREEN']}"
theme[used_end]="{t['GREEN_BR']}"

theme[download_start]="{t['TRACK']}"
theme[download_mid]="{t['ACCENT']}"
theme[download_end]="{t['ACCENT']}"

theme[upload_start]="{t['TRACK']}"
theme[upload_mid]="{t['RED']}"
theme[upload_end]="{t['RED_BR']}"

theme[process_start]="{t['CYAN']}"
theme[process_mid]="{t['ACCENT']}"
theme[process_end]="{t['MAGENTA']}"
""")


# ------------------------------------------------------------------ cava ---
def cava(t):
    w(CFG / "cava/themes/dark_sea", f"""\
[color]
# Regenerated by apply_theme_colors.py on every wallpaper switch
background = '{t['BG']}'
foreground = '{t['FG']}'

gradient = 1
gradient_color_1 = '{t['TRACK']}'
gradient_color_2 = '{t['BORDER']}'
gradient_color_3 = '{t['ACCENT']}'
gradient_color_4 = '{t['ACCENT']}'
gradient_color_5 = '{t['CYAN']}'
gradient_color_6 = '{t['CYAN_BR']}'
gradient_color_7 = '{t['YELLOW']}'
gradient_color_8 = '{t['WARM']}'
""")


# -------------------------------------------------------------- swaylock ---
def swaylock(t):
    bg, track, accent, red = (t[k].lstrip("#") for k in ("BG", "TRACK", "ACCENT", "RED"))
    border, cyan, green, fg = (t[k].lstrip("#") for k in ("BORDER", "CYAN", "GREEN", "FG"))
    w(CFG / "swaylock/config", f"""\
# Regenerated by apply_theme_colors.py on every wallpaper switch.
# screenshots/clock need swaylock-effects, not plain swaylock.
screenshots
effect-blur=7x5
effect-vignette=0.5:0.5
fade-in=0.2
clock
timestr=%H:%M
datestr=%A, %e %B

# Плоский цвет — запасной вариант, если screenshots не сработает.
color={bg}

font=Sans
font-size=24

inside-color={bg}aa
inside-clear-color={track}aa
inside-ver-color={accent}aa
inside-wrong-color={red}aa

indicator-radius=100
indicator-thickness=10

line-use-label=true
line-color=00000000
line-clear-color=00000000
line-ver-color=00000000
line-wrong-color=00000000

ring-color={border}ff
ring-clear-color={cyan}ff
ring-ver-color={green}ff
ring-wrong-color={red}ff

key-hl-color={fg}ff
bs-hl-color={red}ff

text-color={fg}ff
text-clear-color={fg}ff
text-ver-color={bg}ff
text-wrong-color={bg}ff
""")


# ------------------------------------------------------------------- zed ---
def zed(t):
    a = lambda k: t[k] + "ff"
    w(CFG / "zed/themes/dark_sea.json", json.dumps({
        "$schema": "https://zed.dev/schema/themes/v0.2.0.json",
        "name": "Dark Sea",
        "author": "you",
        "themes": [{
            "name": "Dark Sea",
            "appearance": "dark",
            "style": {
                "border": a("BORDER"), "border.variant": a("DARK"),
                "border.focused": a("ACCENT"), "border.selected": a("ACCENT"),
                "border.transparent": "#00000000", "border.disabled": a("DARK"),

                "elevated_surface.background": a("TRACK"),
                "surface.background": a("BG"), "background": a("BG"),

                "element.background": a("TRACK"), "element.hover": a("DARK"),
                "element.active": a("BORDER"), "element.selected": a("DARK"),
                "element.disabled": a("BG"),

                "drop_target.background": t["ACCENT"] + "33",
                "ghost_element.background": "#00000000",
                "ghost_element.hover": a("DARK"), "ghost_element.active": a("BORDER"),
                "ghost_element.selected": a("DARK"),

                "text": a("FG"), "text.muted": a("DIM"),
                "text.placeholder": a("PLACEHOLDER"), "text.disabled": a("PLACEHOLDER"),
                "text.accent": a("ACCENT"),

                "icon": a("FG"), "icon.muted": a("DIM"),
                "icon.disabled": a("PLACEHOLDER"), "icon.accent": a("ACCENT"),

                "status_bar.background": a("BG"), "title_bar.background": a("BG"),
                "toolbar.background": a("BG"), "tab_bar.background": a("BG"),
                "tab.inactive_background": a("BG"), "tab.active_background": a("TRACK"),

                "editor.background": a("BG"), "editor.foreground": a("FG"),
                "editor.gutter.background": a("BG"), "editor.line_number": a("BORDER"),
                "editor.active_line_number": a("FG"),
                "editor.active_line.background": t["TRACK"] + "80",
                "editor.highlighted_line.background": a("TRACK"),
                "editor.wrap_guide": t["BORDER"] + "40",
                "editor.document_highlight.read_background": t["BORDER"] + "60",
                "editor.document_highlight.write_background": t["ACCENT"] + "40",

                "terminal.background": a("BG"), "terminal.foreground": a("FG"),
                "terminal.ansi.black": a("BG"), "terminal.ansi.red": a("RED"),
                "terminal.ansi.green": a("GREEN"), "terminal.ansi.yellow": a("YELLOW"),
                "terminal.ansi.blue": a("ACCENT"), "terminal.ansi.magenta": a("MAGENTA"),
                "terminal.ansi.cyan": a("CYAN"), "terminal.ansi.white": a("FG"),
                "terminal.ansi.bright_black": a("BORDER"), "terminal.ansi.bright_red": a("RED_BR"),
                "terminal.ansi.bright_green": a("GREEN_BR"), "terminal.ansi.bright_yellow": a("YELLOW_BR"),
                "terminal.ansi.bright_blue": a("ACCENT"), "terminal.ansi.bright_magenta": a("MAGENTA_BR"),
                "terminal.ansi.bright_cyan": a("CYAN_BR"), "terminal.ansi.bright_white": a("WARM"),

                "conflict": a("YELLOW"), "created": a("GREEN"), "deleted": a("RED"),
                "error": a("RED"), "hint": a("CYAN"), "info": a("ACCENT"),
                "modified": a("YELLOW"), "success": a("GREEN"), "warning": a("YELLOW"),

                "scrollbar.thumb.background": t["BORDER"] + "80",
                "scrollbar.thumb.hover_background": t["ACCENT"] + "80",
                "scrollbar.track.background": "#00000000",

                "syntax": {
                    "comment": {"color": a("DIM"), "font_style": "italic"},
                    "string": {"color": a("GREEN")},
                    "number": {"color": a("MAGENTA")},
                    "boolean": {"color": a("MAGENTA")},
                    "constant": {"color": a("WARM")},
                    "keyword": {"color": a("ACCENT"), "font_weight": 700},
                    "function": {"color": a("ACCENT")},
                    "type": {"color": a("YELLOW")},
                    "property": {"color": a("FG")},
                    "variable": {"color": a("FG")},
                    "operator": {"color": a("FG")},
                    "punctuation": {"color": a("DIM")},
                    "tag": {"color": a("ACCENT")},
                    "attribute": {"color": a("YELLOW")},
                    "title": {"color": a("WARM"), "font_weight": 700},
                    "emphasis": {"color": a("YELLOW"), "font_style": "italic"},
                },
            },
        }],
    }, indent=2) + "\n")


# ------------------------------------------------------------------ p10k ---
def p10k(t):
    w(HOME / ".p10k.zsh", f"""\
# ~/.p10k.zsh — Powerlevel10k, regenerated by apply_theme_colors.py on every
# wallpaper switch. Написан вручную, без визарда `p10k configure` — не
# переживёт `p10k configure`, только этот скрипт и ручные правки структуры.

'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {{
  emulate -L zsh -o extended_glob

  typeset -g POWERLEVEL9K_MODE=nerdfont-complete
  typeset -g POWERLEVEL9K_ICON_PADDING=moderate
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs newline prompt_char)
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs time)

  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%F{{{t['BORDER']}}}╭─%f'
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX='%F{{{t['BORDER']}}}├─%f'
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%F{{{t['BORDER']}}}╰─%f'
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=

  # dir
  typeset -g POWERLEVEL9K_DIR_BACKGROUND='{t['TRACK']}'
  typeset -g POWERLEVEL9K_DIR_FOREGROUND='{t['WARM']}'
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='{t['FG']}'
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=2

  # vcs (git)
  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND='{t['GREEN']}'
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='{t['BG']}'
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='{t['YELLOW']}'
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='{t['BG']}'
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='{t['CYAN']}'
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='{t['BG']}'
  typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND='{t['BORDER']}'
  typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND='{t['FG']}'

  # prompt_char (цвет промпт-символа по коду выхода последней команды)
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{{VIINS,VICMD,VIVIS,VIOWR}}_FOREGROUND='{t['ACCENT']}'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{{VIINS,VICMD,VIVIS,VIOWR}}_FOREGROUND='{t['RED']}'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{{OK,ERROR}}_VIINS_CONTENT_EXPANSION='❯'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{{OK,ERROR}}_VICMD_CONTENT_EXPANSION='❮'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''

  # status / время выполнения / фоновые задачи / часы (правая часть)
  typeset -g POWERLEVEL9K_STATUS_OK=false
  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND='{t['RED']}'
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND='{t['BG']}'

  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='{t['BORDER']}'
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='{t['WARM']}'

  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='{t['TRACK']}'
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='{t['CYAN']}'

  typeset -g POWERLEVEL9K_TIME_BACKGROUND='{t['BG']}'
  typeset -g POWERLEVEL9K_TIME_FOREGROUND='{t['DIM']}'
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{{%H:%M:%S}}'

  typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true
}}

(( ${{#p10k_config_opts}} )) && setopt ${{p10k_config_opts[@]}}
'builtin' 'unset' 'p10k_config_opts'
""")


# ----------------------------------------------------- targeted patches ----
def patch(path, pattern, replacement, count=0):
    p = Path(path)
    text = p.read_text()
    new_text, n = re.subn(pattern, replacement, text, count=count, flags=re.M)
    if n:
        p.write_text(new_text)


def driftwm_config(t):
    p = CFG / "driftwm/config.toml"
    patch(p, r'^bg_color = ".*"$', f'bg_color = "{t["BG"]}"')
    patch(p, r'^fg_color = ".*"$', f'fg_color = "{t["FG"]}"')
    # The idle-lock swayidle line spawns swaylock with its own hardcoded
    # (no "#") hex args, separate from swaylock/config's own colors above.
    hx = lambda k: t[k].lstrip("#")
    patch(p, r"(swaylock -c )[0-9a-fA-F]{6}", rf'\g<1>{hx("BG")}')
    patch(p, r"(--inside-color )[0-9a-fA-F]{6}", rf'\g<1>{hx("TRACK")}')
    patch(p, r"(--ring-color )[0-9a-fA-F]{6}", rf'\g<1>{hx("BORDER")}')
    patch(p, r"(--text-color )[0-9a-fA-F]{6}", rf'\g<1>{hx("FG")}')
    patch(p, r"(--key-hl-color )[0-9a-fA-F]{6}", rf'\g<1>{hx("ACCENT")}')


def quickshell_theme(t):
    p = CFG / "driftwm/quickshell/Theme.qml"
    for prop, key in (("bg", "BG"), ("border", "BORDER"), ("fg", "FG"),
                       ("track", "TRACK"), ("accent", "ACCENT"), ("warm", "WARM")):
        patch(p, rf'(readonly property color {prop}: )"#[0-9a-fA-F]{{6,8}}"', rf'\1"{t[key]}"')


def zshrc(t):
    p = HOME / ".zshrc"
    rgb = lambda hexcolor: ";".join(str(int(hexcolor.lstrip("#")[i:i + 2], 16)) for i in (0, 2, 4))
    patch(p, r'(di=38;2;)[0-9;]+(?=:)', rf'\g<1>{rgb(t["ACCENT"])}')
    patch(p, r'(bd=38;2;)[0-9;]+(?=:)', rf'\g<1>{rgb(t["BORDER"])}')
    patch(p, r'(cd=38;2;)[0-9;]+(?=:)', rf'\g<1>{rgb(t["BORDER"])}')


def fuzzel(t):
    p = CFG / "fuzzel/fuzzel.ini"
    hx = lambda k: t[k].lstrip("#")
    for key, val in (
        ("background", hx("BG") + "ee"), ("text", hx("FG") + "ff"),
        ("prompt", hx("ACCENT") + "ff"), ("placeholder", hx("BORDER") + "ff"),
        ("input", hx("FG") + "ff"), ("message", hx("BORDER") + "ff"),
        ("match", hx("ACCENT") + "ff"), ("selection", hx("TRACK") + "ff"),
        ("selection-text", hx("WARM") + "ff"), ("selection-match", hx("CYAN") + "ff"),
        ("counter", hx("BORDER") + "ff"), ("border", hx("BORDER") + "ff"),
    ):
        patch(p, rf'^{key}=[0-9a-fA-F]+$', f'{key}={val}')


def reload_apps():
    for cmd in (
        ["pkill", "-SIGUSR2", "waybar"],
        ["swaync-client", "--reload-css"],
        ["driftwm", "msg", "action", "reload-config"],
    ):
        subprocess.run(cmd, capture_output=True)


def main():
    wallpaper_rel = sys.argv[1] if len(sys.argv) > 1 else "dark_sea.glsl"
    t = get_tokens(wallpaper_rel)

    kitty(t); ghostty(t); waybar(t); swaync(t); gtk(t)
    btop(t); cava(t); swaylock(t); zed(t); p10k(t)
    driftwm_config(t); quickshell_theme(t); zshrc(t); fuzzel(t)

    reload_apps()


if __name__ == "__main__":
    main()
